package main

import (
	"fmt"
	"net/http"
	"strings"
)

// signup_page.go renders the three browser pages of the web-signup flow. They are built by
// concatenation rather than html/template because everything interpolated is either ours or
// has been through sanitizeForHTML — and a template would hide that fact rather than make it
// checkable. Every call site below passes a sanitized value.

// signupShell wraps body content in the site chrome so /signup looks like the landing page
// rather than a bolted-on form.
func (s *server) signupShell(title, body string) string {
	return `<!doctype html><html lang=en><head><meta charset=utf-8>
<meta name=viewport content="width=device-width, initial-scale=1">
<title>` + title + ` — mago</title>
<link rel="icon" href="/favicon.svg" type="image/svg+xml">
<link rel="stylesheet" href="/static/site.css">
<style>
.auth { max-width: 34rem; margin: 0 auto; padding: 5rem 1.5rem; }
.auth h1 { font-family: var(--font-display); font-size: 2rem; letter-spacing: -0.02em; margin: 0 0 0.8rem; }
.auth p { color: var(--mut); }
.sso { display: flex; flex-direction: column; gap: 0.8rem; margin: 2rem 0; }
.sso a {
  display: flex; align-items: center; justify-content: center; gap: 0.7rem;
  padding: 0.95rem 1.2rem; border-radius: 0.8rem; text-decoration: none;
  border: 1px solid var(--hairline); background: var(--shell); color: var(--fg);
  font-weight: 600; transition: border-color .4s var(--ease), transform .4s var(--ease);
}
.sso a:hover { border-color: rgba(124,58,237,.55); transform: translateY(-1px); }
.claim-code {
  font-family: var(--font-mono); font-size: 1.6rem; letter-spacing: 0.08em;
  text-align: center; padding: 1rem; margin: 0.6rem 0 1.4rem;
  background: #0b0b12; border: 1px solid rgba(124,58,237,.4); border-radius: 0.8rem;
}
.note { border-left: 2px solid var(--acc); padding-left: 0.9rem; margin: 1.4rem 0; font-size: 0.92rem; }
.warn { border-left-color: #f87171; }
</style></head><body>
<div class="orb orb-a"></div><div class="orb orb-b"></div>
<header><a class="brand" href="/">mago</a></header>
<main class="auth">` + body + `</main>
<footer><div class=foot-row><span>mago — <a href="/">home</a></span></div></footer>
</body></html>`
}

// handleSignupPage is the provider picker. One provider today; the loop is here so adding
// Google is a map entry rather than a template edit.
func (s *server) handleSignupPage(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if !portierConfigured() {
		fmt.Fprint(w, s.signupShell("Sign up", `<h1>Sign-up is not available here</h1>
<p>This deployment has no identity provider configured. You can still create an account from
the CLI with <code>mago register</code>.</p>`))
		return
	}
	var buttons strings.Builder
	for id, label := range portierProviders {
		buttons.WriteString(`<a href="/auth/portier/start?provider=` + id + `">Continue with ` + label + `</a>`)
	}
	fmt.Fprint(w, s.signupShell("Sign up", `<h1>Create your mago account</h1>
<p>Sign in with the account that owns your repositories. We never see your password, and we
ask for no card — the trial runs for 48 hours.</p>
<div class="sso">`+buttons.String()+`</div>
<p class="note">Next you will install the CLI and paste one setup code. The worker runs on your
own machine with your own LLM key — that part is the product, not a limitation.</p>`))
}

// renderClaim is the hand-off page: the account already exists, here is how to attach it to a
// machine. code is generated by us; note and the user's email are sanitized by the caller.
func (s *server) renderClaim(w http.ResponseWriter, u *User, code, note string) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	plan := "48-hour trial"
	if u.Plan == "founding" {
		plan = "Founding operator — free during beta"
	}
	noteHTML := ""
	if note != "" {
		noteHTML = `<p class="note warn">` + note + `</p>`
	}
	fmt.Fprint(w, s.signupShell("Your account is ready", `<h1>Your account is ready</h1>
<p><strong>`+sanitizeForHTML(u.Email)+`</strong> · `+plan+`</p>`+noteHTML+`
<p>Two commands and your first agent is running. The setup code below is single-use and
expires in 15 minutes.</p>
<ol class="steps-list">
  <li><span>Install the CLI</span>
    <code class="cmd">curl -fsSL `+s.appURL+`/install.sh | sh</code></li>
  <li><span>Attach this machine to your account</span>
    <div class="claim-code">`+code+`</div>
    <code class="cmd">mago claim `+code+`</code></li>
  <li><span>Connect your repositories and start working</span>
    <code class="cmd">mago link &amp;&amp; mago serve --relay</code></li>
</ol>
<p class="note">Lost the code? Sign in again from <a href="/signup">/signup</a> and a fresh one
is issued. Stuck? <code>mago worker doctor</code> names whatever is missing.</p>`))
}

// renderSignupError reports a failed sign-in without leaking which part failed. msg is
// sanitized by the caller.
func (s *server) renderSignupError(w http.ResponseWriter, msg string) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.WriteHeader(http.StatusBadRequest)
	fmt.Fprint(w, s.signupShell("Sign-in failed", `<h1>That did not work</h1>
<p>`+msg+`</p>
<div class="sso"><a href="/signup">Try again</a></div>`))
}
